import type { Metadata } from "next"
import { Crimson_Pro, Geist, Geist_Mono, Inter } from "next/font/google"
import "../globals.css"
import Navbar from "@/components/Layout/HeaderComponents/Navbar"
import { client } from "@/sanity/lib/client"
import Footer from "@/components/Layout/FooterComponents/Footer"
import { getServiceItemsLinks } from "@/sanity/queries/services/serviceItem"
import Script from "next/script"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
})

const crimsonPro = Crimson_Pro({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-crimson-pro",
})

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const logo = await client.fetch(`
    *[_type == "generalLayout"][0] {
      logo {
        asset->{
          url,
          metadata {
            dimensions,
            lqip,
            palette
          }
        },
        alt,
        hotspot,
        crop
      },
      footerLogo {
        asset->{
          url,
          metadata {
            dimensions,
            lqip,
            palette
          }
        },
        alt,
        hotspot,
        crop
      },
      companyName,
      }
  `)
  const companyInfo = await client.fetch(`
    *[_type == "generalLayout"][0] {
      email,
      companyName,
      footerText {
        en,
        es  
      },
      socialLinks {
        linkedin,
        github
      }
    }
  `)

  const serviceLinks = await getServiceItemsLinks()

  return (
    <html lang="en">
      <Script
        src={`https://www.googletagmanager.com/gtag/js?id=G-Y3DMZHFV9Z`}
        strategy="lazyOnload"
      />
     <script src="https://analytics.ahrefs.com/analytics.js" data-key="1+Xtrpxb01gBoWyKHrpzhQ" async></script>
      <Script id="ga-setup" strategy="lazyOnload">
        {`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-Y3DMZHFV9Z');
            `}
      </Script>
      <body className={`${crimsonPro.variable} ${inter.variable} antialiased`}>
        <Navbar logo={logo} serviceLinks={serviceLinks} />
        {children}
        <Footer
          logo={logo}
          companyInfo={companyInfo}
          serviceLinks={serviceLinks}
        />
      </body>
    </html>
  )
}
